AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Bluebonnets: CFN Template To Create a Glue Crawler. 

Metadata:
  TemplateName: glue-crawler-stack.yaml
  TemplateType: Glue Crawler
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Agapanthus
  Modification History: 
    - 1.0.0  - May 10, 2023   -- Initial Version.
    
  Resources: 
    - Glue Crawler
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: "Project And Environment:"
      Parameters: 
      - ProjectName
      - Environment
    #################################### Glue Crawler ##############################################
    - Label:
        default: "Glue Crawler Configuration:"
      Parameters:
      - GlueCrawlerName
      - GlueCrawlerRoleName
      - GlueCrawlerDescription
      - GlueCrawlerTablePrefixName
      - GlueDataBucketName
      - GlueCSVDataFolder
      - GlueJSONDataFolder
      # - GlueEventNotificationDataFolder
    ParameterLabels:
      ################################## Project Name and Environment ##############################
    - Label: 
        default: "Project And Environment:"
      ProjectName:
        default: "Project Name."
      Environment:
        default: "Environment Name."
    #################################### Glue Crawler ##############################################
    - Label:
        default: "Glue Crawler Configuration:"
      GlueDatabaseName:
        default: "The Name Of The Glue Database."
      GlueCrawlerName:
        default: "Glue Crawler Name."
      GlueCrawlerRoleName:
        default: "Glue Crawler Role Namex."
      GlueCrawlerDescription:
        default: "Glue Crawler Description."
      GlueCrawlerTablePrefixName:
        default: "Glue Table Prefix."
      GlueDataBucketName:
        default: "Glue Crawler S3 Bucket Name."
      GlueDataFolder:
        default: "The S3 Folder To Store The Datafile."
      GlueEventNotificationDataFolder:
        default: "The S3 Folder To Store The Data To Be Crawled Using S3 Event Notification"
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: project
    Description: "The Project Name."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The Environment Name."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod" 
  ###################################### Glue Crawler ##############################################
  GlueDatabaseName:
    Default: glue-database-name
    Description: "The Glue Database Name."
    Type: String
    MinLength: 3
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  GlueCrawlerName:
    Default: glue-crawler-name
    Description: "The Glue Crawler Name."
    Type: String
    MinLength: 3
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  GlueCrawlerRoleName:
    Default: crawler-role
    Description: "The Name Of The Glue IAM Role."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: "The"
  GlueCrawlerDescription:
    Default: glue crawler description
    Type: String
    MinLength: 0
    MaxLength: 200
    AllowedPattern: "[a-zA-Z0-9-. _]*"
    ConstraintDescription: "The length should be between 30 and 200, must alphanumeric character, space, dot(.), dash(-) or underscore(_)."
  GlueCrawlerTablePrefixName:
    Default: glue-table-prefix
    Description: "The Name Of The Glue Crawler."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "[a-zA-Z-_]*"
    ConstraintDescription: "The length should be between 5 and 30, must alphanumeric character, dash (-) or underscore(_)."
  GlueDataBucketName:
    Default: some-s3-bucket-name
    Description: "The S3 Bucket Base Name For Which Stores The Data File."
    Type: String
    MinLength: 3
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter." 
  GlueCSVDataFolder:
    Default: "input"
    Description: "The Folder To Be Created For Storing The Raw CSV Data."
    Type: String
    MinLength: 3
    MaxLength: 20
    AllowedPattern: "[a-zA-Z-_//]*"
    ConstraintDescription: "The length should be between 3 and 20 and should only contain alphanumeric character, dash(-), underscore (_) or slash (/)."
  GlueJSONDataFolder:
    Default: "input"
    Description: "The Folder To Be Created For Storing The Raw JSON Data."
    Type: String
    MinLength: 3
    MaxLength: 20
    AllowedPattern: "[a-zA-Z-_//]*"
    ConstraintDescription: "The length should be between 3 and 20 and should only contain alphanumeric character, dash(-), underscore (_) or slash (/)."
Resources:
  ###################################### Glue Crawler ##############################################
  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Ref GlueCrawlerName
      Role: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${GlueCrawlerRoleName}" 
      #Classifiers: none, use the default classifier
      Description: !Ref GlueCrawlerDescription
      #Schedule: none, use default run-on-demand
      DatabaseName: !Sub '${GlueDatabaseName}-${Environment}-${AWS::Region}'
      Targets:
        S3Targets:
          # S3 Data Sources Path
          - Path: !Sub "s3://${GlueDataBucketName}/${GlueCSVDataFolder}"
          - Path: !Sub "s3://${GlueDataBucketName}/${GlueJSONDataFolder}"
      TablePrefix: !Ref GlueCrawlerTablePrefixName
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"
      Configuration: "{\"Version\":1.0,\"CrawlerOutput\":{\"Partitions\":{\"AddOrUpdateBehavior\":\"InheritFromTable\"},\"Tables\":{\"AddOrUpdateBehavior\":\"MergeNewColumns\"}}}"
      Tags:
        "ProjectName": !Ref ProjectName
        "Environment": !Ref Environment
Outputs:
  GlueCrawlerArn:
    Description: The Arn Of The Glue Crawler.
    Value: !Ref GlueCrawler

