AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Agapanthus: Root Stack Template To Create A S3 Bucket, Glue Database and  Glue Crawler with two data sources.

Metadata:
  TemplateName: agapanthus-root-stack.yaml
  TemplateType: S3 Bucket / Glue Database / Glue Crawler / SQS Queue
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Agapanthus
  Modification History: 
    - 1.0.0  - May 10, 2023   -- Initial Version.

  Resources: 
    - One S3 Bucket KMS SSE Encryption with three default folders.
    - One Glue Database.
    - One Glue Crawler with two data sources.
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: "Project And Environment:"
      Parameters: 
        - ProjectName
        - Environment
    #################################### S3 Repository Bucket ######################################
    - Label:
        default: "S3 Repository Bucket:"
      Parameters:
      - S3RepositoryBucketName
    #################################### KMS Key ###################################################
    - Label: 
        default: "KMS Configuration:"
      Parameters: 
        - KmsMasterKeyAlias
        # - KmsMasterKeyId
    #################################### S3 Bucket #################################################
    - Label:
        default: "S3 Configuration:"
      Parameters:
      - S3LandingZoneBucketBaseName
      - S3DataBucketFolder
      - S3BucketBlockPublicAcls
      - S3BucketBlockPublicPolicy
      - S3BucketIgnorePublicAcls
      - S3BucketRestrictPublicBuckets
      - S3CustomResourceStackName
    #################################### Glue Database #############################################
    - Label:
        default: "Glue Database Configuration:"
      Parameters:
      - GlueDatabaseInputName
      - GlueDatabaseDescription
    #################################### Glue IAM Role #############################################
    - Label:
        default: "Glue IAM Role Configuration:"
      Parameters:
      - GlueIAMRoleName
      - GlueIAMPolicyName
    #################################### Glue Crawler ##############################################
    - Label:
        default: "Glue Crawler:"
      Parameters:
      - GlueCrawlerName
      - GlueCrawlerDescription
      - GlueCrawlerTablePrefixName
      - GlueCSVDataFolder
      - GlueJSONDataFolder
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Project Name."
      Environment:
        default: "Environment Name."
      ################################## S3 Repository Bucket ######################################
      S3RepositoryBucketName:
        default: "The S3 Bucket Used As Code Repository."
      ################################## KMS Key ###################################################
      KmsMasterKeyAlias:
        default: "KMS Key Alias."
      # KmsMasterKeyId:
      #   default: "KMS Key Id."
      ################################## S3 Bucket #################################################
      S3LandingZoneBucketBaseName:
        default: "S3 Bucket Name."
      S3DataBucketFolder:
        default: "Folder Name."
      S3BucketBlockPublicAcls: 
        default: "Block Public Acls."
      S3BucketBlockPublicPolicy:
        default: "Block Public Policy."
      S3BucketIgnorePublicAcls:
        default: "Ignore Public Acls."
      S3BucketRestrictPublicBuckets:
        default: "Restrict Public Buckets."
      S3CustomResourceStackName:
        default: "S3 Custom Resource Stack."
    #################################### Glue Database #############################################
      GlueDatabaseInputName:
        default: "Glue Database Name."
      GlueDatabaseDescription:
        default: "Glue Database Description."
    #################################### Glue IAM Role #############################################
      GlueIAMRoleName:
        default: "Glue IAM Role Name."
      GlueIAMPolicyName:
        default: "Glue IAM Policy Name."
    #################################### Glue CSV Crawler ##########################################
      GlueCrawlerName:
        default: "Glue Crawler Name."
      GlueCrawlerDescription:
        default: "Glue Crawler Description."
      GlueCrawlerTablePrefixName:
        default: "Glue Table Prefix."
      GlueCSVDataFolder:
        default: "The S3 Folder To Store The CSV Datafile."
      GlueJSONDataFolder:
        default: "The S3 Folder To Store The JSON Datafile."
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: agapanthus
    Description: "The Project Name."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The Environment Name."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"
  ################################## S3 Repository Bucket ######################################
  S3RepositoryBucketName:
    Default: subhamay-projects-repository-us-east-1
    Description: "The S3 Bucket Base Name For The Source Data. The Region And Environment Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 3
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  ###################################### KMS Key ###################################################
  KmsMasterKeyAlias:
    Default: "SB-KMS"
    Description: "The KMS Master Key Alias To Be Used For Server Side Encryption."
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: "The length of the KMS Key Alias should be beteen 5 and 20 and can only contain lowercase alphanumeric characters and dash."
  ###################################### S3 Bucket #################################################
  S3LandingZoneBucketBaseName:
    Default: agapanthus-landing-zone
    Description: "The S3 Bucket Base Name For The Source Data. The Region And Environment Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 3
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  S3DataBucketFolder:
    Default: "input/json, input/csv" ## , input/event-notification/json
    Description: "The Folder To Be Created For Storing The Raw Data. Use Do_not_create If You Do Not Want To Create Any Folder."
    Type: String
    ConstraintDescription: "Should be a comma seperated folder names."
  S3BucketBlockPublicAcls:
    Default: true
    Description: "Allow Block Public Acls"
    Type: String
    AllowedValues: [true, false]
  S3BucketBlockPublicPolicy:
    Default: true
    Description: "Allow Block Public Policy"
    Type: String
    AllowedValues: [true, false]
  S3BucketIgnorePublicAcls:
    Default: true
    Description: "Allow Ignore Public Acls"
    Type: String
    AllowedValues: [true, false]
  S3BucketRestrictPublicBuckets:
    Default: true
    Description: "Allow Restrict Public Buckets"
    Type: String
    AllowedValues: [true, false]
  S3CustomResourceStackName:
    Default: "agapanthus-custom-resource-stack"
    Description: "S3 Custom Resource Stack Name"
    Type: String
  ###################################### Glue Database #############################################
  GlueDatabaseInputName:
    Default: agapanthus-glue-database
    Description: "The Glue Database Name.The Region Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 3
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  GlueDatabaseDescription:
    Default: "Agapanthus Glue Database"
    Description: "The Glue Databased for Demo."
    Type: String
    MinLength: 10
    MaxLength: 200
    AllowedPattern: "[a-zA-Z0-9-. _]*"
    ConstraintDescription: "The length should be between 30 and 200, must alphanumeric character, space, dot dash or underscore."
  ###################################### Glue IAM Role #############################################
  GlueIAMRoleName:
    Default: agapanthus-glue-iam-role
    Description: "The IAM Role Name To Be Used By Glue."
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 10 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  GlueIAMPolicyName:
    Default: agapanthus-glue-iam-policy
    Description: "The IAM Policy Name To Be Used By Glue."
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 10 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  ###################################### Glue Crawler ##############################################
  GlueCrawlerName:
    Default: agapanthus-crawler
    Description: "The Glue Crawler Name."
    Type: String
    MinLength: 3
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  GlueCrawlerDescription:
    Default: The Glue Crawler To Crawl Two Data Sources - One CSV and the other as JSON file.
    Description: Agapanthus Glue Crawler Description.
    Type: String
    MinLength: 0
    MaxLength: 200
    AllowedPattern: "[a-zA-Z0-9-. _]*"
    ConstraintDescription: "The length should be between 30 and 200, must alphanumeric character, space, dot(.), dash(-) or underscore(_)."
  GlueCrawlerTablePrefixName:
    Default: "agapanthus_"
    Description: "The Name Of The Glue Table Prefix."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "[a-zA-Z-_]*"
    ConstraintDescription: "The length should be between 5 and 30, must alphanumeric character, dash (-) or underscore(_)."
  GlueCSVDataFolder:
    Default: "input/csv"
    Description: "The Folder To Be Created For Stroing The CSV Raw Data."
    Type: String
    MinLength: 3
    MaxLength: 20
    AllowedPattern: "[a-zA-Z-_//]*"
    ConstraintDescription: "The length should be between 3 and 20 and should only contain alphanumeric character, dash(-) or underscore (_)."
  GlueJSONDataFolder:
    Default: "input/json"
    Description: "The Folder To Be Created For Stroing The JSON Raw Data."
    Type: String
    MinLength: 3
    MaxLength: 20
    AllowedPattern: "[a-zA-Z-_//]*"
    ConstraintDescription: "The length should be between 3 and 20 and should only contain alphanumeric character, dash(-) or underscore (_)."
Resources:
  ###################################### S3 Bucket #################################################
  AgapanthusS3Bucket:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${S3RepositoryBucketName}.s3.amazonaws.com/0052-agapanthus/cft/nested-stacks/s3-stack.yaml'
      Parameters:  
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        S3LandingZoneBucketBaseName: !Ref S3LandingZoneBucketBaseName
        S3DataBucketFolder: !Ref S3DataBucketFolder
        S3BucketBlockPublicAcls: !Ref S3BucketBlockPublicAcls
        S3BucketBlockPublicPolicy: !Ref S3BucketBlockPublicPolicy 
        S3BucketIgnorePublicAcls: !Ref S3BucketIgnorePublicAcls
        S3BucketRestrictPublicBuckets: !Ref S3BucketRestrictPublicBuckets
        S3CustomResourceStackName: !Ref S3CustomResourceStackName
        S3KmsMasterKeyAlias: !Ref KmsMasterKeyAlias
      TimeoutInMinutes: 15
  ###################################### Glue Database #############################################
  AgapanthusGlueDatabase:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${S3RepositoryBucketName}.s3.amazonaws.com/0052-agapanthus/cft/nested-stacks/glue-database-stack.yaml'
      Parameters:  
        Environment: !Ref Environment
        GlueDatabaseInputName: !Ref GlueDatabaseInputName
        GlueDatabaseDescription: !Ref GlueDatabaseDescription
      TimeoutInMinutes: 15
  ###################################### Glue IAM Role #############################################
  AgapanthusGlueIAMRole:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${S3RepositoryBucketName}.s3.amazonaws.com/0052-agapanthus/cft/nested-stacks/glue-iam-role-stack.yaml'
      Parameters:  
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        GlueIAMRoleName: !Ref GlueIAMRoleName
        GlueIAMPolicyName: !Ref GlueIAMPolicyName
      TimeoutInMinutes: 15
  ###################################### Glue Crawler ##############################################
  AgapanthusGlueCrawler:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - AgapanthusGlueIAMRole
    Properties:
      TemplateURL: !Sub 'https://${S3RepositoryBucketName}.s3.amazonaws.com/0052-agapanthus/cft/nested-stacks/glue-crawler-stack.yaml'
      Parameters:  
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        GlueCrawlerName: !Ref GlueCrawlerName
        GlueDatabaseName: !Ref GlueDatabaseInputName
        GlueCrawlerRoleName: !Ref GlueIAMRoleName
        GlueCrawlerDescription: !Ref GlueCrawlerDescription
        GlueCrawlerTablePrefixName: !Ref GlueCrawlerTablePrefixName
        GlueDataBucketName: !Sub "${S3LandingZoneBucketBaseName}-${Environment}-${AWS::Region}"
        GlueCSVDataFolder: !Ref GlueCSVDataFolder
        GlueJSONDataFolder: !Ref GlueJSONDataFolder
      TimeoutInMinutes: 15
Outputs:
  AgapanthusS3BucketArn:
    Description: Agapanthus S3 Bucket Arn
    Value: !GetAtt AgapanthusS3Bucket.Outputs.S3LandingZoneBucketArn
  AgapanthusGlueDatabaseId:
    Description: Agapanthus Glue Database Id
    Value: !GetAtt AgapanthusGlueDatabase.Outputs.GlueDatabaseId
  AgapanthusGlueIAMRoleArn:
    Description: Agapanthus Glue IAM Role Arn
    Value: !GetAtt AgapanthusGlueIAMRole.Outputs.GlueIAMRoleArn
  AgapanthusCrawlerArn:
    Description: Agapanthus Glue Crawler Arn
    Value: !GetAtt AgapanthusGlueCrawler.Outputs.GlueCrawlerArn
